// generated by stringer -type Token; DO NOT EDIT

package token

import "fmt"

const _Token_name = "ErrorEOFEOLWhitespaceCommaFieldNameFieldValue"

var _Token_index = [...]uint8{0, 5, 8, 11, 21, 26, 35, 45}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
